[package]
name = "component-model-precompile"
version = "0.1.0"
edition = "2024"

[dependencies]
wasmtime = { version = "34.0.1", default-features = false, features = ["runtime", "component-model", "pulley", "cranelift"] }
